version: "3.8"

volumes:
  prometheus_data: {}
  grafana_data: {}

# Networks
networks:
  default:
    driver: bridge

# Services
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - default
    ports:
      - "3000:3000"
    user: "472"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-remote-write-receiver"
      - "--log.level=debug"
    ports:
      - 9090:9090

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - default
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 14250:14250

  otel-collector:
    # using contrib so it includes the loki exporter and service graph exporter
    image: otel/opentelemetry-collector-contrib:latest
    hostname: otel-collector
    container_name: otel-collector
    command: --config=/etc/otel-collector-config.yml
    volumes:
      - ./otel-collector/otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    ports:
      # - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 4317:4317 # OTLP gRPC receiver
      #- 4318:4318 # OTLP HTTP receiver
